### PR TITLE
Add a bug in STM

### LINKED ISSUE #1: Add a bug in STM protocol found using SPIN/Promela
Paper Imbs, D., & Raynal, M. (2010). Software Transactional Memories: An Approach for Multicore Programming. Parallel Computing Technologies contains an acknowledgement to professor Yurii Karpov and his student Alexey Belyaev. They found a bug in STM protocol using SPIN/Promela.

Proofs:

1. https://is.ifmo.ru/present/2012/20120218_model_che%D1%81king_karpov_lecture01.pdf:
image

2. Paper about found bug in Russian: "Верификация алгоритма поддержки транзакционной памяти" - Беляев Алексей Борисович, [PDF](https://github.com/dranov/protocol-bugs-list/files/12370918/verifikatsiya-algoritma-podderzhki-tranzaktsionnoy-pamyati.pdf)

### PR DESCRIPTION
**Pull request by ligurio**
Add a bug in STM
    
1. https://link.springer.com/article/10.1007/s11227-010-0388-0
2. https://cyberleninka.ru/article/n/verifikatsiya-algoritma-podderzhki-tranzaktsionnoy-pamyati
3. https://is.ifmo.ru/present/2012/20120218_model_che%D1%81king_karpov_lecture01.pdf
    
Fixes #1

### CODE REVIEW

**Comment by ligurio** [comment]
@dranov George, could your review?

**Comment by dranov** [comment]
Hi @ligurio. Thanks for the addition and apologies for the delay – my GitHub notification settings were such that I didn't get an e-mail when the PR was submitted.

It looks good in terms of content, but we need a different way of typing the Russian characters. The current `\usepackage[russian]{babel}` makes the bibliography in `table.pdf` Russian:

image

Instead, we need:

```latex
\usepackage[T2A]{fontenc}
\usepackage[main=english, russian]{babel}
```

**I've made the change.**

I also added a `CONTRIBUTING.md` file and updated the `Makefile` to build everything automatically. You might need to follow the install instructions in `CONTRIBUTING.md` to be able to build the project now.

I have also updated the reference, to include translation of the title & source, and transliteration of the name:

```bibtex
@inproceedings {Belyaev2010,
	author = {Alexey Belyaev},
	title = {Верификация алгоритма поддержки транзакционной памяти {[Verifying an algorithm for transactional memory support]}},
	booktitle = {Информатика, телекоммуникации и управление {[Informatics, telecommunications and control]}. 2010. №3 (101)},
	year = {2010},
    url = {https://cyberleninka.ru/article/n/verifikatsiya-algoritma-podderzhki-tranzaktsionnoy-pamyati},
	month = feb,
	language = {russian},
}
```

([By convention](https://library.unimelb.edu.au/recite/referencing-styles/apa7/referencing-non-english-sources) titles in non-Latin alphabets are transliterated into English, but I prefer transliterating names and translating titles, as done above, as it's easier.)

**TODO:**

- [ ] @ligurio: please check the transliteration and translation and revise if needed. Let me know if it's okay so I can merge.
- [ ]  If you have time, you might want to go through https://tex.stackexchange.com/questions/561915/declare-bibliography-entry-in-a-foreign-language-with-translation and see how we can do the multiscript bibliography entry properly.

**Comment by dranov** [comment]
@ligurio are the transliteration and translation OK?

**Comment by ligurio** [comment]
> are the transliteration and translation OK?

It's ok, thanks!

**Comment by ligurio** [comment]
Thanks!

**Pull request merged**
